### ISSUE TITLE
Error trying out test instructions

### ISSUE THREAD

**Issue by chokokatana** [ever-co/ever-traduora#218]
**Describe the bug**
Trying to follow the instructions at https://docs.traduora.com/docs/getting-started#try-it-out.

**To Reproduce**
```
$ git clone https://github.com/traduora/traduora
$ cd traduora/
$ docker-compose up
Creating network "traduora_default" with the default driver
Pulling mysqldb (mysql:5.7)...
5.7: Pulling from library/mysql
69692152171a: Pull complete
1651b0be3df3: Pull complete
951da7386bc8: Pull complete
0f86c95aa242: Pull complete
37ba2d8bd4fe: Pull complete
6d278bb05e94: Pull complete
497efbd93a3e: Pull complete
a023ae82eef5: Pull complete
e76c35f20ee7: Pull complete
e887524d2ef9: Pull complete
ccb65627e1c3: Pull complete
Digest: sha256:a682e3c78fc5bd941e9db080b4796c75f69a28a8cad65677c23f7a9f18ba21fa
Status: Downloaded newer image for mysql:5.7
Pulling traduora (traduora/traduora:latest)...
latest: Pulling from traduora/traduora
cbdbe7a5bc2a: Pull complete
091983d60f65: Pull complete
7bacc183740f: Pull complete
c4a5a5d270d4: Pull complete
9881c9c47703: Pull complete
4549cb3842ea: Pull complete
de39a83780c8: Pull complete
Digest: sha256:4aaf8f7b6bcf8d37715fe85f50021d7d1bb02f1cb4c346930d76d5441df7e1b8
Status: Downloaded newer image for traduora/traduora:latest
Creating traduora_mysqldb_1 ... done
Creating traduora_traduora_1 ... done
Attaching to traduora_mysqldb_1, traduora_traduora_1
mysqldb_1   | 2021-05-21 13:55:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
mysqldb_1   | 2021-05-21 13:55:49+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysqldb_1   | 2021-05-21 13:55:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
mysqldb_1   | 2021-05-21 13:55:50+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
mysqldb_1   |     Remove MYSQL_USER="root" and use one of the following to control the root user password:
mysqldb_1   |     - MYSQL_ROOT_PASSWORD
mysqldb_1   |     - MYSQL_ALLOW_EMPTY_PASSWORD
mysqldb_1   |     - MYSQL_RANDOM_ROOT_PASSWORD
traduora_mysqldb_1 exited with code 1
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:51 PM   [NestFactory] Starting Nest application...
traduora_1  | No email transport configured. Please check the documentation on how to configure the mail service at: https://docs.traduora.com/docs/configuration
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:52 PM   [InstanceLoader] PassportModule dependencies initialized +80ms
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:52 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:52 PM   [InstanceLoader] JwtModule dependencies initialized +1ms
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:52 PM   [InstanceLoader] HttpModule dependencies initialized +1ms
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:52 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +54ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:55 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3014ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:55:58 PM   [TypeOrmModule] Unable to connect to the database. Retrying (3)... +3012ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:01 PM   [TypeOrmModule] Unable to connect to the database. Retrying (4)... +3009ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:04 PM   [TypeOrmModule] Unable to connect to the database. Retrying (5)... +3011ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:07 PM   [TypeOrmModule] Unable to connect to the database. Retrying (6)... +3011ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:10 PM   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3009ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:13 PM   [TypeOrmModule] Unable to connect to the database. Retrying (8)... +3011ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:16 PM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3009ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_1  | [Nest] 1   - 05/21/2021, 1:56:16 PM   [ExceptionHandler] getaddrinfo ENOTFOUND mysqldb +1ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysqldb
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
traduora_1  |     at step (/opt/traduora/node_modules/tslib/tslib.js:139:27)
traduora_1  |     at Object.next (/opt/traduora/node_modules/tslib/tslib.js:120:57)
traduora_traduora_1 exited with code 1
```
**Expected behavior**
Docker compose runs without database errors and app is available at port 8080.

**Environment (please complete the following information):**
Tried on both W10 and OSX 10.14.6

**Additional context**
Tried to modify the `docker-compose.yaml` to change database ports but couldn't make it work.

Changed traduora tag to 0.16.0 and same problem.

**Comment by evereq** [comment]
@chokokatana we did some fixing today regarding Docker / Docker Compose (more specifically so it waits MySQL to start and become available before run API). 

I suggest trying again with the following (from https://github.com/ever-co/ever-traduora/blob/develop/docs/getting-started.md#try-it-out): 

```
git clone https://github.com/ever-co/ever-traduora
cd ever-traduora
docker-compose -f docker-compose.demo.yaml up
```

Note: if you want to build a docker image locally (instead of downloading a prebuilt one), just run `docker-compose up` instead of `docker-compose -f docker-compose.demo.yaml up`.

Please let me know if you need more help,
Ruslan

**Comment by chokokatana** [comment]
Thanks, that works now.
