### ISSUE TITLE
Compile from source error 

### ISSUE THREAD

**Issue by Owned67** [ever-co/ever-traduora#408]
**Describe the bug**
cannot compile

**To Reproduce**
1. git clone https://github.com/ever-co/ever-traduora
2. cd ever-traduora && bin/build.sh
3. bin/start.sh
4. at the end, error appear

**Expected behavior**
```
success Already up-to-date.
Done in 2.37s.
yarn run v1.22.22
$ ng build --prod
Option "--prod" is deprecated: Use "--configuration production" instead.
⠧ Generating browser application bundles (phase: building)...node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/Owned67/ever-traduora/webapp/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/Owned67/ever-traduora/webapp/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

** Environment (please complete the following information):**
 - Device: VPS
 - OS: Debian 11
 - Node.js v18.12.0

**Additional context**

**Comment by Owned67** [comment]
export NODE_OPTIONS=--openssl-legacy-provider and run build.sh solve this
