### ISSUE TITLE
Cannot get stats

### ISSUE THREAD

**Issue by Artdue** [ever-co/ever-traduora#440]
**Describe the bug**
In console code 500
message: "Http failure response for https://{domain}/api/v1/projects/{projectId}/stats: 500 Internal Server Error"
In docker logs:
QueryFailedError: missing FROM-clause entry for table "projectlocale"
    at PostgresQueryRunner.query (/opt/traduora/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.execute (/opt/traduora/node_modules/typeorm/query-builder/QueryBuilder.js:273:20) {
  query: SELECT projectLocale.localeCode AS "localeCode", count(*) AS "translated" FROM "project_locale" "projectLocale" LEFT JOIN "translation" "translations" ON "translations"."project_locale_id"="projectLocale"."id" WHERE "projectLocale"."id" IN ($1, $2) AND "translations"."value" <> '' GROUP BY localeCode,
  parameters: [
    '---',
    '---'
  ],
  driverError: error: missing FROM-clause entry for table "projectlocale"
      at /opt/traduora/node_modules/pg/lib/client.js:535:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/opt/traduora/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)

So it's kind of naming issue, stats won't load and export doesn't work
Tried to rename tables/columns, but new errors appear

**To Reproduce**

It's happening from the moment I choose project

**Expected behavior**
To see stats on the left, under the project name

**Screenshots**

** Environment (please complete the following information):**

- Device: Desctop
- OS: Ubuntu
- Browser: Chrome
- Version: 119.0.6045.124
App was deployed according to documentation, only config was adjusted
Using postgres db
Auth goes fine, but when project is chosen, i

**Additional context**

**Comment by samuelmbabhazi** [comment]
@Artdue ,
For this I would like to have more context, please. I tried to reproduce it with PostgreSQL config as described in the problem, but I do not encounter any problems. The statistics are retrieved without any problems.

can you tell me how to reproduce this, and if possible attach a short video !
